# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4a5de3b1f3595458979a4fa64e57dbd9c8fd27ef47f160e7071ecd8ce1d56d2571f4f319f48adb7abd30cb97c846404754387c90b9f3bc8d25a71721cbfada7

test:
  secret_key_base: 4eed481bd8309fe04e42d8f504b6ecb6b13e960196de7872753f167133be46902f201fd788bbb6dda010d9a1d6b32acd087c7cae4a233d8d577592d84ffedcac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
