# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad65bdc505e670955e4b73f273d1b6712fe24a1e4a3b587b35dbb6f20eb82116c8c26c2617bac01a5035f3e0e9f7697eee766b1606652cee53a3d3f15236552f

test:
  secret_key_base: 56932c0ed829ff0fb1c44f70d213a70c60172c0da57eebf61983b0035e1f3abd2128eaaafa8f1e43cd045e2318ef99ecdba84395a9eac9ab4e712c475e1a79c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
